name: Build and Release Rust Binary

on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build with 'size' profile
        run: cargo build --profile size

      - name: Build with 'performance' profile
        run: cargo build --profile performance

      - name: Build with 'balanced' profile
        run: cargo build --release

      - name: Create GitHub Release
        id: create_release
        uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload 'size' binary to release
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ffetch
          archive: ffetch-size
          target: x86_64-unknown-linux-gnu
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload 'performance' binary to release
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ffetch
          archive: ffetch-performance
          target: x86_64-unknown-linux-gnu
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload 'balanced' binary to release
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ffetch
          archive: ffetch-balanced
          target: x86_64-unknown-linux-gnu
          token: ${{ secrets.GITHUB_TOKEN }}
