name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libxcb1-dev libx11-dev libxext-dev

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg >/dev/null
        sudo apt update
        sudo apt install gh
  
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build release
      run: cargo build --release
    
    - name: Create GitHub Release
      run: |
        gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
        gh release create ${{ github.ref_name }} ./target/release/ffetch --title "Release ${{ github.ref_name }}" --notes "Release notes for ${{ github.ref_name }}"


    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/ffetch
        asset_name: ffetch
        asset_content_type: application/octet-stream
