name: Release
on:
  push:
    tags:
      - 'v*.*.*'
  create:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxcb-shm0-dev libx11-dev
    - name: Build
      run: cargo build --release
    - name: Create archive
      run: |
        BINARY_NAME=$(grep '^name = ' Cargo.toml | head -1 | cut -d '"' -f2)
        mkdir release
        cp target/release/$BINARY_NAME release/
        [ -f README.md ] && cp README.md release/
        [ -f LICENSE ] && cp LICENSE release/
        [ -f CHANGELOG.md ] && cp CHANGELOG.md release/
        tar -czf $BINARY_NAME-linux.tar.gz -C release .
        
        # ASCII dizini varsa ayrı tar oluştur
        if [ -d "ascii" ]; then
          echo "ASCII directory found, listing contents:"
          ls -la ascii/
          echo "Creating ascii.tar.gz..."
          tar -czf ascii.tar.gz ascii/ || echo "Failed to create ascii.tar.gz"
          if [ -f ascii.tar.gz ]; then
            echo "ascii.tar.gz created successfully"
            ls -la ascii.tar.gz
          else
            echo "ascii.tar.gz NOT created!"
          fi
        else
          echo "ASCII directory not found"
          ls -la .
        fi
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.tar.gz
        body_path: CHANGELOG.md
